services:
  document-intelligence-frontend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: document-intelligence-image-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: document-intelligence-frontend