services:
  demoname-frontend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: imagename-frontend:latest
    ports:
      - "3000:3000"
    restart: always
    container_name: demoname-frontend